### ISSUE TITLE
Airfoil definitions seem incorrect

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/dromader#2]
The PZL Dromader does not fly in accordance with specifications for airspeed. 
The first glance inspection of the dromader.tmd file indicates that the airfoil specification for the wings are wrong.
Yes the wing should be NACA 4412 and NACA 4416 but the values used for AirfoilRoot, AirfoilMid and AirfoilTip are all the same and these do not correspond to either the 4412 or 4416.  In particular the Cl0 value is obviously too low at 0.15
http://airfoiltools.com/polar/details?polar=xf-naca4412-il-1000000
https://ntrs.nasa.gov/api/citations/19740013521/downloads/19740013521.pdf
Based on this I would guess at
NACA 4412 Cl0 = 0.5
NACA 4416 Cl0 = 0.4

**Comment by krzysk1** [comment]
Agree. CL0 parameters corrected

**Comment by krzysk1** [comment]
I set NACA 4412 for all wings
                <[float64][Cl0][0.4833]>
                <[float64][Cd0][0.00678]>
                <[float64][Cm0][-0.1032]>
In fact:  
PZL M-18 Dromader - NACA 4412,
PZL M-18A Dromader - NACA 4416,
